"""Add nickname and identity fields to Profile

Revision ID: ae4be9e4cf1a
Revises: 001
Create Date: 2026-01-22 23:30:20.561741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae4be9e4cf1a'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('nickname', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('current_identity', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('ideal_identity', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('core_problem', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'core_problem')
    op.drop_column('profiles', 'ideal_identity')
    op.drop_column('profiles', 'current_identity')
    op.drop_column('profiles', 'nickname')
    # ### end Alembic commands ###
